default:
  place: Mafalda
  time:
    minutes: 780
#    13hs
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chegu
logging:
  level:
    org.springframework.web:DEBUG